# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com
   - RGL_USE_NULL: true

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - freeglut3-dev
  - xvfb
  - xserver-xorg-core
  - xserver-xorg
  - xorg
  - openbox
  - xauth
  - libssh2-devel

r_binary_packages:
    - plyr
    - rARPACK
    - rgl

r_github_packages:
  - hadley/devtools
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - Rscript -e 'devtools::load_all(); devtools::test()'
